name: Build & Publish
on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run:
          docker run --rm -e 'version=${{ github.ref_name }}' -e 'shortversion=${{ github.ref_name }}' -v
          "$(pwd):/data" blang/latex pdflatex "Connor Bell CV.tex"

      - uses: actions/upload-artifact@v4
        with:
          name: Connor Bell CV.pdf
          path: Connor Bell CV.pdf

      - uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ github.ref_name }}
          name: CV Version ${{ github.ref_name }}
          artifacts: Connor Bell CV.pdf
